---

  - name: install required packages
    action: >
      {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
    with_items:
      - wget
      - perl

  - name: Subscribe to official Dell yum repos
    shell: wget -q -O - http://linux.dell.com/repo/hardware/dsu/bootstrap.cgi | bash

  - name: install DSU
    yum: name=dell-system-update state=present

  - name: Install OMSA
    yum: name={{ meta_pkg_install }} state=present
    notify:
    - start omsa

